# Generated by Django 3.2.3 on 2022-07-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='bs_icon',
            field=models.CharField(choices=[('headset', 'fas fa-headset'), ('briefcase', 'fas fa-briefcase')], default='fas fa-headset', max_length=30),
        ),
    ]
