# Generated by Django 3.2.3 on 2022-07-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_project_bs_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='img',
            field=models.ImageField(default='da-img-1.jpg', upload_to='project-img'),
        ),
        migrations.AlterField(
            model_name='project',
            name='bs_icon',
            field=models.CharField(choices=[('fas fa-headset', 'headset icon'), ('fas fa-briefcase', 'briefcase icon')], default='fas fa-headset', max_length=30),
        ),
    ]
