# Generated by Django 3.2.3 on 2022-07-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20220704_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='bs_icon',
            field=models.CharField(choices=[('fas fa-briefcase', 'briefcase icon'), ('fas fa-headset', 'headset icon')], default='fas fa-headset', max_length=30),
        ),
    ]
