# Generated by Django 4.2.9 on 2024-01-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_project_bs_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='big_text',
            field=models.TextField(default='RHA Solutions PLC.'),
        ),
    ]
